name: Upload lamdbda zip to S3

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Package and sync lambda to S3
        uses: cloud-sniper/python-package-to-s3-action@v2-alpha-debug
        with:
          package_name: 'numpy'
          bucket_name: 'cloud-sniper-artifacts-us-east-1'
          bucket_prefix: 'lambdas'

