name: Upload lamdbda zip to S3

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install requirements and package lambda function
        run: |
          python -m venv lambda
          source lambda/bin/activate
          pip install -r requirements.txt -t ./python
          deactivate
          cd python
          zip -r python.zip *
          mkdir build
          mv python.zip ./build


      - name: Copy zip file to the public bucket
        run: |
          aws s3 sync ./python/build s3://cloud-sniper-artifacts-us-east-1/lambdas/

