name: Upload lamdbda zip to S3

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Package Lambda Function
        run: | 
          INPUT_PACKAGE_NAME="numpy"
          INPUT_WORKDIR="src"

          build() {
              python -m venv lambda
              source lambda/bin/activate
              pip install -r requirements.txt -t ./python
              deactivate
          }

          package() {
              cd python
              zip -r $INPUT_PACKAGE_NAME.zip *
              mkdir build
              mv $INPUT_PACKAGE_NAME.zip ./build
          }

          if [ -d "$INPUT_WORKDIR/$INPUT_PACKAGE_NAME" ]; then
              cd $INPUT_WORKDIR/$INPUT_PACKAGE_NAME
          else
              cd $INPUT_WORKDIR
          fi

          build
          package
          
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add build/
          git commit -m "generated"
          git push


